#-------------------------Подстановка имен----------------------#
substitutions:
  devicename: ble-nas
  device: ble_nas
  up_device: "BLE NAS"
  board: esp32dev
  framework: arduino
  update: 60s
  xiaomi_LYWSD02: "LYWSD02"
#---------------------------Тип платы ESP-----------------------#
esp32:
  board: $board
  framework:
    type: $framework
#---------------------------Имя платы ESP-----------------------#
esphome:
  name: ${devicename}
  project:
    name: "Espressif.ESP32_Devkitc_V4"
    version: "0.0.12"
#--------------------------Параметры WiFi-----------------------#
wifi:
  ssid: !secret ssid
  password: !secret pass
  manual_ip:
    static_ip: !secret ble_nas_ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true    
#-----------------------Параметры веб-сервера-------------------#
web_server:
  port: 80

logger:
#---------------------------Параметры API-----------------------#
api:
  encryption:
    key: !secret ble_nas_api
#---------------------------Параметры OTA-----------------------#
ota:
  password: !secret ble_nas_ota
#---------------------------Параметры BLE-----------------------#  
esp32_ble_tracker:

#==============================Сенсоры==========================#
sensor:
#-----------------------Мощность сигнала WiFi-------------------#
  - platform: wifi_signal
    name: "${up_device} WiFi signal"
    id: ${device}_wifi 
    update_interval: ${update}
    icon: mdi:wifi-strength-2
#--------------------Конвертация времени работы-----------------#
  - platform: uptime
    id: ${device}_uptime
    internal: true
    update_interval: ${update}
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device}_uptime_text
            state: !lambda |-
              int seconds = round(id(${device}_uptime).raw_state);
              int days = seconds / (24 * 3600);
              seconds = seconds % (24 * 3600);
              int hours = seconds / 3600;
              seconds = seconds % 3600;
              int minutes = seconds /  60;
              seconds = seconds % 60;
              return (
                (days ? String(days) + "д " : "") +
                (hours ? String(hours) + "ч " : "") +
                (minutes ? String(minutes) + "м " : "") +
                (String(seconds) + "с")
              ).c_str();
#-----------------------Сенсоры часов Xiaomi--------------------#
  - platform: xiaomi_lywsd02
    mac_address: E7:2E:00:F0:8C:41
    temperature:
      name: "${xiaomi_LYWSD02} Temperature"
      icon: mdi:thermometer-bluetooth
    humidity:
      name: "${xiaomi_LYWSD02} Humidity"
      icon: mdi:water-percent
    battery_level:
      name: "${xiaomi_LYWSD02} Battery"
      icon: mdi:battery-50-bluetooth
#-----------------------Мощность сигнала BLE--------------------#      
  - platform: ble_rssi
    mac_address: E7:2E:00:F0:8C:41
    name: "${xiaomi_LYWSD02} RSSI"
    icon: mdi:bluetooth-transfer
    
#=========================Текстовые сенсоры=====================#
text_sensor:
#---------------------------Время работы------------------------#
  - platform: template
    name: "${up_device} uptime"
    id: ${device}_uptime_text
    icon: mdi:clock-plus-outline

#=========================Бинарные сенсоры======================#
binary_sensor:
#------------------------Статус подключения---------------------#
  - platform: status
    name: "${up_device} status"
    id: ${device}_status

#=========================Переключатели=========================#
switch:
#---------------------Удаленный рестарт ESP---------------------#
  - platform: restart
    id: ${device}_restart
    name: "${up_device} restart"
    icon: "mdi:restart"
