#========================== Подстановка имен =========================#
substitutions:
  devicename: input-meter
  device: input_meter
  update: 60s

#============================== Тип ESP ==============================#
esp8266:
  board: esp01_1m

#========================= Параметры прошивки ========================#
esphome:
  name: ${devicename}
  project:
    name: "Espressif.Esp8266-07s"
    version: "1.3.7"
  on_boot:
    priority: 600
    then:
      - switch.turn_on: ${device}_main_switch
  build_path: /config/esphome/build/input_meter
#------------------------- Внешние библиотеки ------------------------#
external_components:
  - source: github://dentra/esphome-components

#=========================== Параметры WiFi ==========================#
wifi:
  ssid: !secret ssid
  password: !secret pass
  manual_ip:
    static_ip: !secret inp_met_ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true

#========================= Параметры логгера =========================#
logger:
  baud_rate: 0

#=========================== Параметры API ===========================#
api:
  encryption:
    key: !secret inp_met_api
  reboot_timeout: 0s

#=========================== Параметры OTA ===========================#
ota:
  password: !secret inp_met_ota

#======================== Параметры отладчика ========================#
debug:
  update_interval: ${update}

#======================= Параметры 1wire/Dallas ======================#
dallas:
  - pin: 4
    id: dallas_wire
    update_interval: ${update}

#=========================== Параметры UART ==========================#
uart:
  rx_pin: 3
  tx_pin: 1
  baud_rate: 9600

#========================= Параметры Tuya MCU ========================#
tuya:
  on_datapoint_update:
    - sensor_datapoint: 6
      datapoint_type: raw
      then:
        - lambda: |-
            id(${device}_voltage).publish_state((x[0] << 8 | x[1]) * 0.1);
            id(${device}_current).publish_state((x[3] << 8 | x[4]) * 0.001);
            id(${device}_power).publish_state((x[6] << 8 | x[7]) * 0.1);

#============= Синхронизация времени через HomeAssistant =============#
time:
  - platform: homeassistant
    id: ${device}_esptime

#================ Обновление статуса реле по интервалу ===============#
interval:
  - interval: 1min
    then:
      - lambda: |-
          if (id(${device}_main_switch).state) {
            id(${device}_main_switch_status).publish_state("ON");
          } else {
            id(${device}_main_switch_status).publish_state("OFF");
          }

#============================== Сенсоры ==============================#
sensor:
#----------------------- Мощность сигнала WiFi -----------------------#
  - <<: !include add_config/wifi_strength.config.yaml
#--------------------- Конвертация времени работы --------------------#
  - <<: !include add_config/uptime_convert.config.yaml
#---------------------------- Датчики TUYA ---------------------------#
#................... Общий датчик энергомониторинга ..................#
  - platform: "energy_monitoring"
    power: ${device}_power
    voltage: ${device}_voltage
    current: ${device}_current
    apparent_power:
      id: ${device}_apparent_power_tuya
      internal: true
    reactive_power:
      id: ${device}_reactive_power_tuya
      internal: true
    power_factor:
      id: ${device}_power_factor_tuya
      internal: true
#.................. Общее потребления электроэнергии .................#
  - platform: "tuya"
    sensor_datapoint: 1
    id: ${device}_total
    name: "${devicename} Total energy"
    unit_of_measurement: "Wh"
    icon: mdi:home-lightning-bolt-outline
    device_class: "energy"
#............................. Напряжение ............................#
  - platform: template
    id: ${device}_voltage
    name: "${devicename} Voltage"
    unit_of_measurement: "V"
    filters:
      - median:
         window_size: 11
         send_every: 7
         send_first_at: 2
    icon: mdi:alpha-v-circle-outline
    device_class: "voltage"
#............................. Сила тока .............................#
  - platform: template
    id: ${device}_current
    name: "${devicename} Amperage"
    accuracy_decimals: 1
    unit_of_measurement: "A"
    filters:
      - median:
         window_size: 11
         send_every: 7
         send_first_at: 2
    icon: mdi:alpha-a-circle-outline
    device_class: "current"
#.......................... Полная мощность ..........................#
  - platform: template
    id: ${device}_apparent_power
    name: "${devicename} Apparent power"
    unit_of_measurement: "VA"
    accuracy_decimals: 0
    lambda: |-
      return id(${device}_apparent_power_tuya).state;
    icon: mdi:flash
    device_class: "apparent power"
#......................... Активная мощность .........................#
  - platform: template
    id: ${device}_power
    name: "${devicename} Active power"
    unit_of_measurement: "W"
    accuracy_decimals: 0
    filters:
      - median:
         window_size: 11
         send_every: 2
         send_first_at: 2
    icon: mdi:flash
    device_class: "power"
#........................ Реактивная мощность ........................#
  - platform: template
    id: ${device}_reactive_power
    name: "${devicename} Reactive power"
    unit_of_measurement: "var"
    accuracy_decimals: 0
    lambda: |-
      return id(${device}_reactive_power_tuya).state;
    icon: mdi:flash
    device_class: "reactive power"
#........................ Коэффициент мощности .......................#
  - platform: template
    id: ${device}_power_factor
    name: "${devicename} Power factor"
    unit_of_measurement: "%"
    filters:
      - multiply: 100
    lambda: |-
      return id(${device}_power_factor_tuya).state;
    icon: mdi:math-cos
    device_class: "power factor" 
#........................... Частота в сети ..........................#
  - platform: "tuya"
    sensor_datapoint: 103
    id: ${device}_frequency
    name: "${devicename} Frequency"
    unit_of_measurement: "Hz"
    icon: mdi:math-sin
    device_class: "frequency"
#............... Верхний порог отключения по напряжению ..............#
  - platform: "tuya"
    sensor_datapoint: 101
    id: ${device}_voltage_limit_max
    name: "${devicename} Max voltage limit"
    unit_of_measurement: "V"
    icon: mdi:tag-arrow-up-outline
#............... Нижний порог отключения по напряжению ...............#
  - platform: "tuya"
    sensor_datapoint: 102
    id: ${device}_voltage_limit_min
    name: "${devicename} Min voltage limit"
    unit_of_measurement: "V"
    icon: mdi:tag-arrow-down-outline
#...................... ХРЕН ЗНАЕТ ЧТО ЭТО ТАКОЕ .....................#
  - platform: "tuya"
    id: ${device}_NODATA_1
    sensor_datapoint: 13
    internal: true
  - platform: "tuya"
    id: ${device}_NODATA_2
    sensor_datapoint: 104
    internal: true
#------------------------------ DS18B20 ------------------------------#
  - platform: dallas
    address: 0x673c01d607c85428
    id: ${device}_temp
    name: "${devicename} Board t°"
    device_class: "temperature"

#============================= Светодиоды ============================#
light:
#------------------------- Светодиод статуса -------------------------#
  - platform: status_led
    id: ${device}_led
    internal: true
    pin:
      number: 2
      inverted: true

#=========================== Переключатели ===========================#
switch:
#--------------- Включение общего реле электроснабжения --------------#
  - platform: "tuya"
    id: ${device}_main_switch
    name: "${devicename} Main switch"
    switch_datapoint: 16
    icon: mdi:power

#========================= Текстовые сенсоры =========================#
text_sensor:
#---------------------------- Время работы ---------------------------#
  - <<: !include add_config/uptime.config.yaml
#------------------------- Информация о сети -------------------------#
  - <<: !include add_config/wifi_info.config.yaml
#----------------------- Причина перезагрузки ------------------------#
  - <<: !include add_config/reset_reason.config.yaml
#----------------------- Статус включения реле -----------------------#
  - platform: template
    id: ${device}_main_switch_status
    name: "${devicename} Main switch status"
    icon: mdi:toggle-switch-variant-off

#========================== Бинарные сенсоры =========================#
binary_sensor:
#------------------------- Статус подключения ------------------------#
  - <<: !include add_config/status.config.yaml

#=============================== Кнопки ==============================#
button:
#----------------------- Удаленный рестарт ESP -----------------------#
  - <<: !include add_config/restart.config.yaml
