#========================== Подстановка имен =========================#
substitutions:
  devicename: polka-svet
  device: polka_svet
  update: 60s

#============================== Тип ESP ==============================#
esp8266:
  board: d1_mini

#========================= Параметры прошивки ========================#
esphome:
  name: ${devicename}
  project:
    name: "Wemos.D1 mini v3"
    version: "1.4.6"
  build_path: /config/esphome/build/polka_svet

#=========================== Параметры WiFi ==========================#
wifi:
  ssid: !secret ssid
  password: !secret pass
  manual_ip:
    static_ip: !secret plk_svet_ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true

#========================= Параметры логгера =========================#
logger:
  baud_rate: 0

#=========================== Параметры API ===========================#
api:
  encryption:
    key: !secret plk_svet_api
  reboot_timeout: 0s

#=========================== Параметры OTA ===========================#
ota:
  password: !secret plk_svet_ota

#======================== Параметры отладчика ========================#
debug:
  update_interval: ${update}


#============================== Сенсоры ==============================#
sensor:
#----------------------- Мощность сигнала WiFi -----------------------#
  - <<: !include add_config/wifi_strength.config.yaml
#--------------------- Конвертация времени работы --------------------#
  - <<: !include add_config/uptime_convert.config.yaml

#=========================== Переключатели ===========================#
switch:
#----------------------- Реле не задействовано -----------------------#
  - platform: gpio
    id: ${device}_rel1
    pin:
      number: 14
      inverted: yes
    internal: true 
#----------------------- Реле яркого освещения -----------------------#
  - platform: gpio
    id: ${device}_rel2  
    name: "${devicename} Panel light"
    pin:
      number: 12
      inverted: yes
#---------------------- Реле тусклого освещения ----------------------#
  - platform: gpio
    id: ${device}_rel4  
    name: "${devicename} Night light"
    pin:
      number: 15
      inverted: yes
#---------------------- Реле бокового освещения ----------------------#
  - platform: gpio
    id: ${device}_rel3  
    name: "${devicename} Side light"
    pin:
      number: 13
      inverted: yes
#------------------------ Сигнальный светодиод -----------------------#
  - platform: gpio
    id: ${device}_LED
    pin:
      number: 16
    internal: true

#========================= Текстовые сенсоры =========================#
text_sensor:
#---------------------------- Время работы ---------------------------#
  - <<: !include add_config/uptime.config.yaml
#------------------------- Информация о сети -------------------------#
  - <<: !include add_config/wifi_info.config.yaml
#----------------------- Причина перезагрузки ------------------------#
  - <<: !include add_config/reset_reason.config.yaml

#========================== Бинарные сенсоры =========================#
binary_sensor:
#------------------------- Статус подключения ------------------------#
  - <<: !include add_config/status.config.yaml
#---------------------- Кнопка яркого освещения ----------------------#
  - platform: gpio
    id: ${device}_butn4  
    pin:
      number: 5
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
      - switch.toggle: ${device}_rel2
      - switch.turn_on: ${device}_LED
    on_release:
      then:
      - switch.turn_off: ${device}_LED
    internal: true
#--------------------- Кнопка тусклого освещения ---------------------#
  - platform: gpio
    id: ${device}_butn3  
    pin:
      number: 4
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
      - switch.toggle: ${device}_rel4
      - switch.turn_on: ${device}_LED
    on_release:
      then:
      - switch.turn_off: ${device}_LED
    internal: true
#--------------------- Кнопка бокового освещения ---------------------#
  - platform: gpio
    id: ${device}_butn1  
    pin:
      number: 2
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
      - switch.toggle: ${device}_rel3
      - switch.turn_on: ${device}_LED
    on_release:
      then:
      - switch.turn_off: ${device}_LED
    internal: true
#---------------------- Кнопка общего отключения ---------------------#
  - platform: gpio
    id: ${device}_butn2  
    pin:
      number: 0
      inverted: true
      mode: INPUT_PULLUP
    on_press:
      then:
      - switch.turn_off: ${device}_rel1
      - switch.turn_off: ${device}_rel2
      - switch.turn_off: ${device}_rel3
      - switch.turn_off: ${device}_rel4      
      - switch.turn_on: ${device}_LED
    on_release:
      then:
      - switch.turn_off: ${device}_LED
    internal: true

#=============================== Кнопки ==============================#
button:
#----------------------- Удаленный рестарт ESP -----------------------#
  - <<: !include add_config/restart.config.yaml
