#========================== Подстановка имен =========================#
substitutions:
  devicename: ups-pc
  device: ups_pc
  update: 60s

#============================== Тип ESP ==============================#
esp32:
  board: esp32dev
  framework:
    type: esp-idf

#========================= Параметры прошивки ========================#
esphome:
  name: ${devicename}
  project:
    name: "espressif.ESP32_Devkitc_V4"
    version: "1.4.9"
  build_path: /config/esphome/build/ups_pc

#=========================== Параметры WiFi ==========================#
wifi:
  ssid: !secret ssid
  password: !secret pass
  manual_ip:
    static_ip: !secret ups_pc_ip
    gateway: 192.168.1.1
    subnet: 255.255.255.0
  fast_connect: true

#========================= Параметры логгера =========================#
logger:
  baud_rate: 0

#=========================== Параметры API ===========================#
api:
  encryption:
    key: !secret ups_pc_api
  reboot_timeout: 0s

#=========================== Параметры OTA ===========================#
ota:
  password: !secret ups_pc_ota

#======================== Параметры отладчика ========================#
debug:
  update_interval: ${update}

#======================= Параметры 1wire/Dallas ======================#
dallas:
  - pin: 14
    id: dallas_wire
    update_interval: ${update}

#=============================== Modbus ==============================#
modbus:

#=========================== Параметры UART ==========================#
uart:
  id: ${device}_pzem_uart
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  stop_bits: 2

#==================== Настройка выхода ШИМ-сигнала ===================#
output:
  - platform: ledc
    id: ${device}_fan_pwm
    pin: 32
    frequency: 20000Hz
    min_power: 30%
    max_power: 70%

#============================== Сенсоры ==============================#
sensor:
#----------------------- Мощность сигнала WiFi -----------------------#
  - <<: !include add_config/wifi_strength.config.yaml
#--------------------- Конвертация времени работы --------------------#
  - <<: !include add_config/uptime_convert.config.yaml
#---------------------------- PZEM - 004T ----------------------------#
  - platform: pzemac
#.................. Общее потребления электроэнергии .................#
    energy:
      id: ${device}_energy
      name: "${devicename} Total energy"
      unit_of_measurement: "kWh"
      filters:
      - multiply: 0.001
      icon: mdi:sigma
      device_class: "energy"
#............................. Напряжение ............................#
    voltage:
      id: ${device}_voltage
      name: "${devicename} Voltage"
      unit_of_measurement: "V"
      icon: mdi:alpha-v-circle-outline
      device_class: "voltage"
#............................. Сила тока .............................#
    current:
      id: ${device}_current
      name: "${devicename} Amperage"
      unit_of_measurement: "A"
      icon: mdi:alpha-a-circle-outline
      device_class: "current"
#.............................. Мощность .............................#
    power:
      id: ${device}_power
      name: "${devicename} Power"
      unit_of_measurement: "W"
      icon: mdi:home-lightning-bolt-outline
      device_class: "power"
#........................ Коэффициент мощности .......................#
    power_factor:
      id: ${device}_pf
      name: "${devicename} Power factor"
      unit_of_measurement: "%"
      accuracy_decimals: 0
      filters:
      - multiply: 100
      icon: mdi:math-cos
      device_class: "power factor"
#........................... Частота в сети ..........................#
    frequency:
      id: ${device}_frequency
      name: "${devicename} Frequency"
      unit_of_measurement: "Hz"
      icon: mdi:math-sin
      device_class: "frequency"
    update_interval: ${update}
#------------------------------ DS18B20 ------------------------------#
  - platform: dallas
    address: 0x9f540cc70264ff28
    id: ${device}_batt_1
    name: "${devicename} Battery t° 1"
    device_class: "temperature"
  - platform: dallas
    address: 0x7f673ec70264ff28
    id: ${device}_batt_2
    name: "${devicename} Battery t° 2"
    device_class: "temperature"
  - platform: dallas
    address: 0x1212e5c10264ff28
    id: ${device}_trans_1
    name: "${devicename} Trans t° 1"
    device_class: "temperature"
    on_value:
      then:
        - lambda: |-
            if (id(${device}_power).state < 100) {
              auto call = id(${device}_fan_speed).turn_off();
              call.perform();  }
            else  {
              auto call = id(${device}_fan_speed).turn_on();
              call.set_speed((id(${device}_trans_1).raw_state)+20);
              call.perform(); }
    on_raw_value:
      then:
        - text_sensor.template.publish:
            id: ${device}_fan_speed_text
            state: !lambda |-
              if (id(${device}_fan_speed).state) {
                int fan_speed = round(id(${device}_fan_speed).speed)*55;
                return (
                  (to_string(fan_speed) + " rpm")
                  ).c_str();
              } else {
                return "OFF"; }
  - platform: dallas
    address: 0x309c04c10264ff28
    id: ${device}_trans_2
    name: "${devicename} Trans t° 2"
    device_class: "temperature"
#---------------- ESP32 внутренний датчик температуры ----------------#
  - platform: internal_temperature
    id: ${device}_int_temp
    name: "${devicename} ESP t°"
    device_class: "temperature"

#============================ Вентиляторы ============================#
fan:
  - platform: speed
    id: ${device}_fan_speed
    name: "${devicename} Fan"
    output: ${device}_fan_pwm

#=========================== Переключатели ===========================#
switch:
#-------- Сброс общего потребления электроэнергии PZEM - 004T --------#
  - platform: uart
    uart_id: ${device}_pzem_uart
    id: ${device}_pzem_reset_switch
    data: [0x01, 0x42, 0x80, 0x11]

#========================= Текстовые сенсоры =========================#
text_sensor:
#---------------------------- Время работы ---------------------------#
  - <<: !include add_config/uptime.config.yaml
#------------------------- Информация о сети -------------------------#
  - <<: !include add_config/wifi_info.config.yaml
#----------------------- Причина перезагрузки ------------------------#
  - <<: !include add_config/reset_reason.config.yaml
#------------------------ Обороты вентилятора ------------------------#
  - platform: template
    id: ${device}_fan_speed_text
    name: "${devicename} Fan speed"
    icon: mdi:fan-auto

#========================== Бинарные сенсоры =========================#
binary_sensor:
#------------------------- Статус подключения ------------------------#
  - <<: !include add_config/status.config.yaml

#=============================== Кнопки ==============================#
button:
#----------------------- Удаленный рестарт ESP -----------------------#
  - <<: !include add_config/restart.config.yaml
#-------- Сброс общего потребления электроэнергии PZEM - 004T --------#
  - platform: template
    id: ${device}_pzem_reset
    name: "${devicename} PZEM reset"
    on_press:
      then:
        - switch.turn_on: ${device}_pzem_reset_switch
    icon: mdi:delete-restore
